map:
  url: //dapi.kakao.com/v2/maps/sdk.js?appkey=6854e3cfd8b163da4794e921ba87d43b&autoload=false

i18n:
  baseUrl: /

socket:
  host: localhost
  peerPath: /myapp
  protocol: http
  namespace: maps
  port: 8080
socketUrl: http://localhost:8080/maps
